<div class="modal fade" id="modal-new" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;
                </button>
                <h4 class="modal-title"><?= ucfirst($this->translate('Add address')) ?></h4>
            </div>
            <div class="modal-body">
                <fieldset>                    
                    <form data-svp="#gmapsstreetviewpano" data-svm="#gmapsstreetviewmap" data-clone-field="[data-clone=add-company-address]" data-clone-target="#form-company-address" class="form-horizontal" action="/<?= $this->module_name ?>/add-address.json<?= $this->companyModel->getCurrentPeopleCompany() ? '?company_id=' . $this->companyModel->getCurrentPeopleCompany()->getId() : '' ?>" method="POST">                        
                        <div class="row">
                            <div class="form-suggestion">
                                <?= $this->translate('Company Address'); ?>
                            </div>
                            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
                                <div class="input-group">                                    
                                    <input data-address-nickname="address-nickname" name="address-nickname" type="text" value="<?= $this->translate('Main Address') ?>" placeholder="<?= $this->translate('Enter alias of your address') ?>" class="form-control input-md" required>
                                </div>                        
                            </div>                                
                            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                                <div class="input-group">                                    
                                    <input data-default-contry="Brasil" data-cep="cep" data-mask="({mask: '99999-999','clearIncomplete': true})" name="cep" data-postmon="address-search" type="text" placeholder="<?= $this->translate('Enter CEP of your address') ?>" class="form-control input-md" required>
                                </div>
                            </div>                                
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                <div class="input-group">                                    
                                    <input data-street="street" name="street" type="text" placeholder="<?= $this->translate('Enter address of your Company') ?>" class="panoramio-search form-control input-md" required readonly>
                                </div>
                            </div>        
                            <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
                                <div class="input-group">                                    
                                    <input data-address-number="address-number" name="address-number" type="text" placeholder="<?= $this->translate('Enter address number') ?>" class="panoramio-search form-control input-md" required>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                                <div class="input-group">                                    
                                    <input data-complement="complement" name="complement" type="text" placeholder="<?= $this->translate('Enter complement of your address') ?>" class="form-control input-md">
                                </div>                        
                            </div>                                
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                                <div class="input-group">
                                    <span class="input-group-addon" id="basic-addon4">
                                        <i class="fa fa-key" aria-hidden="true"></i></span>
                                    <input data-district="district" name="district" type="text" placeholder="<?= $this->translate('Enter district of your address') ?>" class="panoramio-search form-control input-md" required readonly>
                                </div>                        
                            </div>
                            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                                <div class="input-group">                                    
                                    <input data-city="city" name="city" type="text" placeholder="<?= $this->translate('Enter city of your address') ?>" class="panoramio-search form-control input-md" required readonly>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
                                <div class="input-group">                                                                        
                                    <input data-state="state" name="state" type="text" placeholder="<?= $this->translate('Enter state of your address') ?>" class="panoramio-search form-control input-md" required readonly>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                                <div class="input-group">                                                                        
                                    <input data-country="country" name="country" type="text" placeholder="<?= $this->translate('Enter country of your address') ?>" class="panoramio-search form-control input-md" required readonly>
                                </div>                        
                            </div>
                        </div>
                        <div class="text-center">
                            <input type="hidden" name="lat" data-lat="lat">
                            <input type="hidden" name="lng" data-lng="lng">
                            <button data-clone-field="[data-clone=add-company-address]" data-clone-target="#form-company-address" data-add="/<?= $this->module_name ?>/add-address.json<?= $this->companyModel->getCurrentPeopleCompany() ? '?company_id=' . $this->companyModel->getCurrentPeopleCompany()->getId() : '' ?>" name="add-address" type="submit" class="btn btn-success pull-right">
                                <?= ucfirst($this->translate('Add address')) ?>
                            </button>   
                            <div class="clearfix"></div>
                        </div>
                    </form>
                    <div id="gmapsstreetview" class="row">
                        <span class="line-street-view pull-left"> </span>
                        <div id="gmapsstreetviewpano" class="gmapsstreetviewpano col-xs-12 col-sm-12 col-md-6 col-lg-6"></div>
                        <div id="gmapsstreetviewmap" class="gmapsstreetviewmap col-xs-12 col-sm-12 col-md-6 col-lg-6"></div>                        
                    </div>
                </fieldset>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>