<div class="row">    
    <div class="col-xs-12">
        <div class="card">
            <div class="card hovercard">
                <div class="card-background">                    
                    <img class="profile-img card-bkimg lazy-load" src="<?= $this->_currentCompany->getImage() ? $this->_currentCompany->getImage()->getUrl() : $this->default_company_logo ?>">                    
                </div>
                <div class="useravatar">
                    <img src="<?= $this->_currentCompany->getImage() ? $this->_currentCompany->getImage()->getUrl() : $this->default_company_logo ?>" class="">
                </div>
                <div class="card-info"> <span class="card-title"><?= $this->_currentCompany->getAlias() ?></span>
                </div>
            </div>
            <ul class="nav nav-tabs tab-stats">                
                <li role="company-details" class="active">
                    <a href="#company-details" aria-controls="company-details" role="tab" data-toggle="tab" aria-expanded="false">
                        <span class="glyphicon glyphicon-earphone"></span> <?= $this->translate('Copany details') ?>
                    </a>
                </li>
                <li role="company-contacts" class="">
                    <a href="#company-contacts" aria-controls="company-contacts" role="tab" data-toggle="tab" aria-expanded="false">
                        <span class="glyphicon glyphicon-earphone"></span> <?= $this->translate('Copany contacts') ?>
                    </a>
                </li>
                <li role="company-adress" class="">
                    <a href="#company-adress" aria-controls="company-adress" role="tab" data-toggle="tab" aria-expanded="true">                        
                        <span class="glyphicon glyphicon-home"></span> <?= $this->translate('Copany adress') ?>
                    </a>
                </li>
                <li role="company-documents" class="">
                    <a href="#company-documents" aria-controls="company-documents" role="tab" data-toggle="tab" aria-expanded="true">                        
                        <span class="glyphicon glyphicon-home"></span> <?= $this->translate('Copany documents') ?>     
                    </a>
                </li>

            </ul>                        
            <div class="card-body tab-content">                
                <div role="tabpanel" class="tab-pane active" id="company-details">
                    Details
                </div>
                <div role="tabpanel" class="tab-pane" id="company-contacts">
                    <?= $this->render("company/form/company-contacts.phtml"); ?>
                </div>
                <div role="tabpanel" class="tab-pane" id="company-adress">
                    <?= $this->render("company/form/company-adress.phtml"); ?>
                </div>
                <div role="tabpanel" class="tab-pane" id="company-documents">
                    <?= $this->render("company/form/company-documents.phtml"); ?>
                </div>

            </div>
        </div>         
    </div>
</div>