<div class="row">
    <div class="col-xs-12">
        <div class="card">
            <div class="panel-body">                                
                <button type="button" title="<?= $this->translate('Add new ' . $this->module_name) ?>" class="btn btn-success pull-right" data-add-form="/<?= $this->module_name ?>/add-company.form<?= $this->companyModel->getCurrentPeopleCompany() ? '?company_id=' . $this->companyModel->getCurrentPeopleCompany()->getId() : '' ?>">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                    <?= $this->translate('Add') ?>
                </button>                
                <legend><?= $this->translate(ucfirst($this->module_name)) ?></legend>                        
                <div class="col-lg-3 col-sm-6 highlight hidden clone" data-clone="add-<?= $this->module_name ?>" id="<?= $this->module_name ?>-{id}">
                    <a href="/<?= $this->module_name ?>/{id}">
                        <div class="user-card hoveruser-card">                    
                            <div class="card-background user-cardheader">                    
                                <img class="user-cardheader profile-img card-bkimg lazy-loaded lazy-load"  src="<?= $this->default_company_logo ?>">
                            </div>
                            <div class="avatar">
                                <img alt="{name}" src="<?= $this->default_company_logo ?>">
                            </div>
                            <div class="info">
                                <div class="title">
                                    <a href="/<?= $this->module_name ?>/{id}">{name}</a>
                                </div>                
                                <!--<div class="desc">({ddd}) {phone}</div>-->
                                <!--<div class="desc">{email}</div>-->
                            </div>                
                        </div>
                    </a>
                </div> 

                <table class="datatable table table-striped primary" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th><?= $this->translate('ID') ?></th>
                            <th><?= $this->translate('CNPJ') ?></th>
                            <th><?= $this->translate('Company alias') ?></th>
                            <th><?= $this->translate('Company name') ?></th>
                            <th><?= $this->translate('E-Mail') ?></th>
                            <th><?= $this->translate('Phone') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $name = 'getPeople' . ucfirst($this->module_name);
                        $name_child = 'get' . ucfirst($this->module_name);
                        foreach ($this->userModel->getUserCompany()->$name() AS $people) {
                                ?>   
                                <tr id="people-<?= $people->$name_child()->getId() ?>">
                                    <td><a href="/<?= $this->module_name ?>/<?= $people->$name_child()->getId() ?>">#<?= $people->$name_child()->getId() ?></a></td>    
                                    <td>
                                        <?php
                                        if ($people->$name_child()->getDocument()) {
                                            foreach ($people->$name_child()->getDocument() AS $document) {
                                                if ($document->getDocumentType()->getDocumentType() == 'CNPJ') {
                                                    echo Core\Helper\Format::maskNumber("##.###.###/####-##", $document->getDocument());
                                                }
                                            }
                                        }
                                        ?>
                                    </td>    
                                    <td><?= $people->$name_child()->getAlias() ?></td>
                                    <td><?= $people->$name_child()->getName() ?></td>    
                                    <td>
                                        <?php foreach ($people->$name_child()->getEmail() AS $email) { ?>
                                            <?= $email->getEmail() ?>
                                        <?php } ?></td>  
                                    <td>
                                        <?php foreach ($people->$name_child()->getPhone() AS $phone) { ?>
                                            (<?= $phone->getDdd() ?>) <?= $phone->getPhone() ?>
                                        <?php } ?>
                                    </td>  
                                </tr>  
                        <?php } ?>                            
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>