<?php
$data = isset($form['data']) ? $form['data'] : array();
$fields = isset($form['fields']) ? $form['fields'] : array();
if ($fields) {
    ?>
    <form class="api-form" action="<?= '/' . ((isset($data['id']) && $data['id']) ? $form['form_name'] . '/id/' . $data['id'] : $form['form_name'] ) . '.form' ?>" method="POST" name="form-<?= $form['form_name'] ?>" role="form" data-childs='<?= json_encode(array_keys($form['childs'])) ?>'>
        <input name="method" value="<?= $form['method'] ?>" type="hidden">         
        <?php foreach ($fields AS $key => $field) { ?>
            <?php if ($key == 'id') { ?>
                <input value="<?= (isset($data) && isset($data[strtolower($key)])) ? $data[strtolower($key)] : null ?>" id="input-<?= $key ?>" name="<?= $key ?>" type="hidden" data-propreties='<?= json_encode($field) ?>' placeholder="Enter <?= ucfirst($key) ?>">
            <?php } elseif (!isset($data[strtolower($key)]) || (isset($data[strtolower($key)]) && !is_array($data[strtolower($key)]))) { ?>
                <div class="form-group">
                    <label id="label-<?= $key ?>" for="input-<?= $key ?>"><?= ucfirst($key) ?>: </label>
                    <input value="<?= (isset($data) && isset($data[strtolower($key)])) ? $data[strtolower($key)] : null ?>" id="input-<?= $key ?>" name="<?= $key ?>" type="text" data-propreties='<?= json_encode($field) ?>' placeholder="Enter <?= ucfirst($key) ?>">
                </div>
            <?php } ?>
        <?php } ?>
        <button type="submit" class="btn btn-default">Save</button>        
    </form>
    <?php if (isset($data) && isset($data['id']) && $data['id']) { ?>
        <form onSubmit="return confirmDelete('<?= ucfirst($form['form_name']) ?>')" action="<?= '/' . $form['form_name'] . '.form' ?>" method="POST" name="form-<?= $form['form_name'] ?>" role="form">
            <input name="method" value="DELETE" type="hidden"> 
            <input value="<?= $data['id'] ?>" id="delete-id" name="id" type="hidden">
            <button type="submit" class="btn btn-default">Delete</button>   
        </form>
        <?php
    }
}
?>
<script>
    function confirmDelete(name) {
        if (!confirm('Really remove this ' + name + '?')) {
            return false;
        }
    }
</script>