<?php if (isset($response['form']) && $response['form']) { ?>
    <div class = "modal fade" id = "modal-<?= $this->form['form_name'] . '-' . ( $data['id'] ? $data['id'] : 'new' ) ?>" role = "dialog">
        <div class = "modal-dialog modal-lg">
            <div class = "modal-content">
                <div class = "modal-header">
                    <button type = "button" class = "close" data-dismiss = "modal">&times;
                    </button>
                    <h4 class = "modal-title"><?= ucfirst($this->form['form_name']) ?></h4>
                </div>
                <div class="modal-body">
                    <div class="show-messages"></div>
                    <?php $this->form = $response['form']; ?>
                    <?php include(dirname(__FILE__) . '/form.phtml'); ?>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
    <?php
} else {
    echo '<pre>';
    print_r($response);
    echo '</pre>';
} 