<div class="app-container app-login" data-need-login="true">    
    <div class="flex-center">        
        <div class="app-body create-account-body" <?= $this->action_name == 'login' ? 'style="display: none;"' : '' ?>>
            <div class="app-block">
                <div class="app-form">
                    <div class="form-suggestion">                                                
                        <?= $this->translate('Create Account'); ?>
                    </div>
                    <form id="create-account-form" class="form-horizontal" data-success-url="/user/profile" action="<?= $this->companyModel->getPeopleDomain()->getDomainType() == 'cfc' ? '/user/create-account.json' : '/user/create-corporate-account.json' ?>" method="POST"  >
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">
                                <i class="fa fa-paper-plane" aria-hidden="true"></i></span>
                            <input id="name" name="name" type="text" placeholder="<?= $this->translate('Enter your name') ?>" class="form-control input-md" required>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon2">
                                <i class="fa fa-user" aria-hidden="true"></i></span>
                            <input id="username" data-user-in-use="/user/user-in-use/username/" data-mask-regex="({regex: '[.a-za-zA-Z0-9]{3,15}'})" name="username" type="text" placeholder="<?= $this->translate('Enter your username') ?>" class="form-control input-md" required>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon3">
                                <i class="fa fa-envelope" aria-hidden="true"></i></span>
                            <input id="email" data-mask="({mask: '*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{2,6}][.*{1,2}]',greedy: false,onBeforePaste: function (pastedValue, opts) {pastedValue = pastedValue.toLowerCase();return pastedValue.replace('mailto:', '');},definitions: {'*': {validator:'[0-9A-Za-z!#$%&\'*+/=?^_`{|}~\-]',cardinality: 1,casing: 'lower'}}})" name="email" type="text" placeholder="<?= $this->translate('Enter your e-mail') ?>" class="form-control input-md" required>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon4">
                                <i class="fa fa-phone" aria-hidden="true"></i></span>
                            <input id="ddd" size="2" data-mask="({mask: '(99)',keepStatic: true})" name="ddd" type="text" placeholder="<?= $this->translate('DDD') ?>" class="form-control input-md" style="border-right: 1px solid #dfe6e8;" required>
                            <span class="input-group-addon" id="basic-addon5">
                                <i class="fa fa-phone" aria-hidden="true"></i></span>
                            <input id="phone" data-mask="({mask: ['9999-9999', '99999-9999'],keepStatic: true})" name="phone" type="text" placeholder="<?= $this->translate('Enter your phone') ?>" class="form-control input-md" required>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon6">
                                <i class="fa fa-key" aria-hidden="true"></i></span>
                            <input id="password" name="password" type="password" data-rule-minlength="5" data-rule-maxlength="15" placeholder="<?= $this->translate('Enter a password') ?>" class="form-control input-md" required>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon7">
                                <i class="fa fa-check" aria-hidden="true"></i></span>
                            <input id="password" name="confirm-password" type="password"  placeholder="<?= $this->translate('Confirm your Password') ?>" class="form-control input-md" required>
                        </div>
                        <div class="text-center">                                    
                            <button data-success-url="<?= $this->login_referrer ?: '/user/profile' ?>" data-save="/user/create-account.json" id="signup" name="signup" class="btn btn-success btn-submit"><?= $this->translate('Register') ?></button>
                        </div>
                    </form>
                    <!--
                    <div class="form-line">
                        <div class="title">OR</div>
                    </div>
                    <div class="form-footer">
                        <button type="button" class="btn btn-default btn-sm btn-social __facebook">
                            <div class="info">
                                <i class="icon fa fa-facebook-official" aria-hidden="true"></i>
                                <span class="title">Register w/ Facebook</span>
                            </div>
                        </button>
                    </div>
                    -->
                    <button data-show=".login-body" data-hide=".create-account-body" data-load-script='{"user-default-login":"\/assets\/js\/user\/default\/login"}' class="pull-left" href="/user/login"><?= $this->translate('Login') ?></button>
                    <button class="pull-right" href="/user/forgot-password"><?= $this->translate('Forgot password ?') ?></button>
                </div>
            </div>
        </div>
        <div class="app-body login-body" <?= $this->action_name == 'create-account' ? 'style="display: none;"' : '' ?>>            
            <div class="app-block">
                <div class="app-form">
                    <div class="form-header">                        
                        <div class="profile-image-container">
                            <img class="profile-image lazy-loaded" data-default-image-profile="<?= $this->default_user_image_profile ?>" src="<?= $this->default_user_image_profile ?>">
                        </div>
                        <div class="app-brand">                            
                            <img class="lazy-loaded logo-login" alt="<?= $this->translate('Application Name') ?>" src="<?= $this->defaultCompany->getImage()->getUrl() ?>">
                        </div>
                    </div> 
                    <div class="row username-container">
                        <h4>&nbsp;
                            <span class="user-name" style="display: none"></span>
                            &nbsp;</h4>
                    </div>
                    <form data-success-url="<?= $this->login_referrer ?: '/' . $this->module_name ?>" id="login-form" class="form-horizontal" action="/<?= $this->module_name ?>/login.json" method="POST"  >
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">
                                <i class="fa fa-user" aria-hidden="true"></i></span>              
                            <input data-valide-ajax="true" data-get-image-profile="/user/get-image-profile/username/" id="username" data-mask-regex="({regex: '[.a-za-zA-Z0-9]{3,15}'})" data-rule-minlength="3" data-rule-maxlength="15" name="username" type="text" placeholder="<?= $this->translate('Enter your Username') ?>" class="form-control input-md profile-username" required>                            
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon2">
                                <i class="fa fa-key" aria-hidden="true"></i></span>
                            <input id="password" name="password" type="password" placeholder="<?= $this->translate('Enter a password') ?>" class="form-control input-md" required>
                        </div>
                        <div class="text-center">                            
                            <button data-save="/<?= $this->module_name ?>/login.json" data-success-url="<?= $this->login_referrer ?: '/' . $this->module_name ?>" id="login" name="login" class="btn btn-success btn-submit"><?= $this->translate('Login') ?></button>                            
                        </div>
                    </form>
                    <!--
                                        <div class="form-line">
                                            <div class="title">OR</div>
                                        </div>
                                        <div class="form-footer">
                                            <button type="button" class="btn btn-default btn-sm btn-social __facebook">
                                                <div class="info">
                                                    <i class="icon fa fa-facebook-official" aria-hidden="true"></i>
                                                    <span class="title">Login with Facebook</span>
                                                </div>
                                            </button>
                                        </div>
                    -->
                    <button class="pull-left" data-load-script='{"user-default-create-account":"\/assets\/js\/user\/default\/create-account"}' data-show=".create-account-body" data-hide=".login-body"><?= $this->translate('Create Account') ?></button>       
                    <button class="pull-right" href="/<?= $this->module_name ?>/forgot-password"><?= $this->translate('Forgot password ?') ?></button>
                </div>                
            </div>            
        </div>
        <div class="app-footer">            
        </div>
    </div>    
</div>
